# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: BUILD_X86

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: config/x86/config
  FEEDS_FILE: config/x86/feeds
  TZ: Asia/Shanghai

jobs:
  build_openwrt:
    name: Build OpenWrt firmware
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync tree jq
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h
          cat /proc/cpuinfo
          free -m
          

      - name: Clone Source Code
        run: |
          df -hT $PWD
          git config --global user.email "git@github.com"
          git config --global user.name "GitHub"
          git clone $REPO_URL -b $REPO_BRANCH openwrt
          echo "OPENWRTROOT=$PWD/openwrt/" >> $GITHUB_ENV
          echo "strDate=$(TZ=UTC-8 date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Update feeds
        run: |
          cp $FEEDS_FILE $OPENWRTROOT/feeds.conf.default
          cd $OPENWRTROOT
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          cp $CONFIG_FILE $OPENWRTROOT/.config
          cd $OPENWRTROOT
          make defconfig

      - name: Make download
        run: |
          cd $OPENWRTROOT
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          cd $OPENWRTROOT
          make -j$(nproc) || make -j1 V=s
          cp ./bin/targets/x86/64/sha256sums ./bin/targets/x86/64/openwrt-x86-64.sha256sums
          sed -e '/feeds.buildinfo/d' -e '/config.buildinfo/d' -e '/version.buildinfo/d'  -i ./bin/targets/x86/64/openwrt-x86-64.sha256sums
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./bin

      - name: Deliver target
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_targets
          path: ./openwrt/bin/targets/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./openwrt/bin/packages/

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{env.OPENWRTROOT}}/bin/targets/x86/64/openwrt-x86-64-generic-*
          tag: ${{env.strDate}}
          file_glob: true
          overwrite: true
          release_name: ${{env.strDate}} 自动发布
